### ISSUE TITLE
Unable to retrieve light groups within 750ms

### ISSUE THREAD

**Issue by doruksart** [tagyoureit/homebridge-luxor#10]
Once in a while, when I reboot my Hoobs hub, the Luxor plugin is unable to retrieve the light groups from the Luxor controller. When this happens, all previously configured light groups are deleted from my Homekit. I have to keep rebooting Hoobs until the plugin can fetch the light groups again. See the error below. Maybe 750ms is too short in my setup? Is there a way to configure/extend that time out setting? 

I am using homebridge-luxor 4.0.0 on Hoobs 4.0.100

9/18/2021, 9:57:10 AMHOOBSLuxorFound Controller named luxor-2 of type ZD.
9/18/2021, 9:57:10 AMHOOBSLuxorAssigning ZD Controller to IP 192.168.X.XX
9/18/2021, 9:57:11 AMHOOBSLuxorERRORError communicating with controller luxor-2. URL GroupListGet.json.
	Error: timeout of 750ms exceeded
9/18/2021, 9:57:11 AMHOOBSLuxorERRORwas not able to retrieve light groups from controller.
Error: timeout of 750ms exceeded
Error: timeout of 750ms exceeded

**Comment by tagyoureit** [comment]
The timeout errors just happen on occasion.  The plugin logs them, but just keeps trying again until it connects.  There should be no need to reboot.

You can play around with changing the timeout by changing the value in the file `./dist/controller/BaseController.js` approximately line 103 `timeout: 750`.  In my previous testing I've found that the controller responds very quickly, or not at all.  When I made the timeout longer then Homebridge would complain that the plugin wasn't responsive.

I've never tried with Hoobs so can't say if that has anything to do with losing the groups, but when the plugin does remove lights/groups/etc. it will put a corresponding message in the logs.  The fact that you aren't seeing that is a bit strange and therefore may have to do with something underlying in Hoobs vs Homebridge.

**Comment by tagyoureit** [comment]
This is also now a setting in the config of the plugin.  Closing this since there hasn't been any activity in a while.
