### ISSUE TITLE
Luxor needs to be rebooted

### ISSUE THREAD

**Issue by jredner** [tagyoureit/homebridge-luxor#3]
If I leave this plugin running, ultimately after a day or so, the Luxor app no longer can communicate with the system.   The problem is resolved by power cycling the Luxor controller.

**Comment by jredner** [comment]
I created a workaround to this solution in the meantime here:

https://github.com/jredner/luxor-homebridge-server

**Comment by tagyoureit** [comment]
Hi, I haven't worked with the Homebridge platform in a while, but never experienced this myself (or #2) that you also opened.  Can you provide some more details on what is making this slow?

I'm also not clear if your workaround is to be used in conjunction with this plug-in or if it is a complete replacement of this one.

**Comment by tagyoureit** [comment]
Unfortunately, I gave up on HomeKit a while ago.  :-( . I'm mostly spending my time with SmartThings these days.  If I ever get back into it, I'll look at this, but if your workaround is performant than its a great workaround!
