### ISSUE TITLE
Receiving Significant Errors When Running

### ISSUE THREAD

**Issue by tylerleppek** [tagyoureit/homebridge-luxor#9]
[homebridge-luxor] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

The link specified tells me to share the message with the Plugin Developer. Let me know how I can help.

**Comment by tagyoureit** [comment]
Please upload any relevant logs and the type of controller/lights that you are running.

**Comment by npeach** [comment]
Hey there. Really appreciate this plugin. I am running a Luxor ZDC. I have two issues that pop up from time to time. the first, is that the zones and themes keep popping up in favorites seemingly everytime homebridge service stops/starts. Not a big deal, but I have about 15 zones and 20 themes. Takes a while to move them to the proper room/screen.

Below are several rows of logs. I see these in homebridge but I dont seem to have any issues seeing/controlling the lights.

thx!

8/8/2021, 10:50:22 PM [Luxor] Error communicating with controller lxtwo-219287. URL ColorListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 10:50:22 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 10:53:23 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 10:53:23 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:04:55 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:04:55 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:06:26 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:06:26 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:09:57 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:09:57 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:30:01 PM [Luxor] Error communicating with controller lxtwo-219287. URL ColorListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:30:01 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:30:32 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:30:32 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:31:33 PM [Luxor] Error communicating with controller lxtwo-219287. URL ColorListSet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:31:33 PM [Luxor] Front Wall Washers colorListSet error: Error: timeout of 750ms exceeded
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Pavilion Steps@@On] The read handler for the characteristic 'On' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Pavilion Steps@@Brightness] The read handler for the characteristic 'Brightness' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Pavilion Wall@@On] The read handler for the characteristic 'On' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Pavilion Wall@@Brightness] The read handler for the characteristic 'Brightness' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front MB and Wall@@On] The read handler for the characteristic 'On' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front MB and Wall@@Brightness] The read handler for the characteristic 'Brightness' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front Crepe Myrtle@@On] The read handler for the characteristic 'On' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front Crepe Myrtle@@Brightness] The read handler for the characteristic 'Brightness' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front Maple@@On] The read handler for the characteristic 'On' was slow to respond!
8/8/2021, 11:31:33 PM [HOOBS 0DB8@Front Maple@@Brightness] The read handler for the characteristic 'Brightness' was slow to respond!
8/8/2021, 11:31:34 PM [Luxor] Error communicating with controller lxtwo-219287. URL ColorListSet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:31:34 PM [Luxor] Front Maple colorListSet error: Error: timeout of 750ms exceeded
8/8/2021, 11:32:35 PM [Luxor] Error communicating with controller lxtwo-219287. URL ThemeListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:32:35 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:37:07 PM [Luxor] Error communicating with controller lxtwo-219287. URL ColorListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:37:07 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded
8/8/2021, 11:40:38 PM [Luxor] Error communicating with controller lxtwo-219287. URL GroupListGet.json.
	Error: timeout of 750ms exceeded
8/8/2021, 11:40:38 PM [Luxor] lxtwo-219287 error: Error: timeout of 750ms exceeded

**Comment by tagyoureit** [comment]
In general, plugins don't have any control whatsoever around what is marked as a favorite.  I would bring this up in the main Homebridge repo as an issue.

Most of the timeout errors happen when there is no response from the Luxor controller.  The timeouts from the controller lead to Homebridge thinking the plugin is slow to respond.  So long as there are no issues controlling the lights/themes, you can safely ignore these messages.
